MyShhop.WebUI/Controllers/BasketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyShhop.Core.Contracts;
using MyShhop.Core.Models;

namespace MyShhop.WebUI.Controllers
{
    public class BasketController : Controller
    {
        IRepository<Customer> customers;
        IBasketService basketService;
        IOrderService orderService;

        public BasketController(IBasketService BasketService,IOrderService OrderService, IRepository<Customer> Customers)
        {
            this.basketService = BasketService;
            this.orderService = OrderService;
            this.customers = Customers;
        }

        // GET: Basket
        public ActionResult Index()
        {
            var model = basketService.GetBasketItems(this.HttpContext);
            return View(model);
        }
        public ActionResult AddToBasket(string Id)
        {
            basketService.AddToBasket(this.HttpContext, Id);
            return RedirectToAction("Index");
        }
        public ActionResult RemoveFromBasket(string Id)
        {
            basketService.RemoveFromBasket(this.HttpContext, Id);
            return RedirectToAction("Index");
        }
        public PartialViewResult BasketSummary()
        {
            var basketSummary = basketService.GetBasketSummary(this.HttpContext);
            return PartialView(basketSummary);
        }
        public ActionResult Checkout()
        {
            Customer customer = customers.Collection().FirstOrDefault(c => c.Email == User.Identity.Name);
            if (customer != null)
            {
                Order order = new Order()
                {
                    Email = customer.Email,
                    City = customer.City,
                    State = customer.State,
                    Street = customer.Street,
                    FirstName = customer.FirstName,
                    Surname = customer.LastName,
                    ZipCode = customer.ZipCode
                };
                return View(order);
            }
            else {
                return RedirectToAction("Error"); 
            }
        }

        [HttpPost]
        [Authorize]
        public ActionResult Checkout(Order order)
        {
            var basketItems = basketService.GetBasketItems(this.HttpContext);
            order.OrderStatus = "Order Created";
            order.Email = User.Identity.Name;
            //Process Payment
            order.OrderStatus = "Payment Processed";
            orderService.CreateOrder(order, basketItems);
            basketService.ClearBasket(this.HttpContext);

            return RedirectToAction("Thank You", new { OrderId = order.Id });
        }

        public ActionResult ThankYou(string OrderId)
        {
            ViewBag.OrderId = OrderId;
            return View();
        }

    }
}

MyShhop.WebUI/Controllers/HomeController.cs
using MyShhop.Core.Contracts;
using MyShhop.Core.Models;
using MyShhop.Core.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyShhop.WebUI.Controllers
{
    public class HomeController : Controller
    {
        IRepository<Product> context;
        IRepository<ProductCategory> productCategories;

        public HomeController(IRepository<Product> productContext, IRepository<ProductCategory> productCategoriesContext)
        {
            context = productContext;
            productCategories = productCategoriesContext;
        }
        public ActionResult Index(string Category = null)
        {
            List<Product> products;
            List<ProductCategory> categories = productCategories.Collection().ToList();
            if(Category == null)
            {
                products=context.Collection().ToList();
            }
            else
            {
                products = context.Collection().Where(p => p.Category == Category).ToList();
            }

            ProductListViewModel Model = new ProductListViewModel();
            Model.Product = products;
            Model.ProductCategories = categories;

            return View(Model);
        }

        public ActionResult Details(string Id){
            Product product = context.Find(Id);
            if(product == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(product);
            }
        }
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MyShhop.WebUI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MyShhop.WebUI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MyShhop.WebUI/Views/Home/Details.cshtml
@model MyShhop.Core.Models.Product

@{
    ViewBag.Title = Model.Name+"Details";
}

<h2>@Html.DisplayFor(model=>model.Name)</h2>

<div>
    <div class="col-md-2">
        <img class="img-responsive" src="~/Content/ProductImages/@Model.Image"/>
    </div>
    <div class="col-md-10">
        <dl class="dl-horizontal">




            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                $@Html.DisplayFor(model => model.Price)
            </dd>
            <dt></dt>
            <dt><a href="@Url.Action("AddToBasket","Basket",new {Id=Model.Id})" class="btn btn-default">Add to Basket</a></dt>

            <dt></dt>
            <dd> @Html.ActionLink("Back to list", "Index") </dd>


        </dl>
    </div>
    </div>
    <div class="col-md-12" clearfix></div>

MyShhop.WebUI/Views/Home/Index.cshtml
@model MyShhop.Core.ViewModels.ProductListViewModel

@{
    ViewBag.Title = "Home Page";
}

<h1>Products</h1>
<div class=" col-md-2">
    <h4>Filter by Category</h4>
    <div class="list-group">
        @Html.ActionLink("All", "Index", null, new { @class = Request["Category"] == null? "list-group-item active":"list-group-item" })
        @foreach(var cat in Model.ProductCategories)
            {
                @Html.ActionLink(cat.Category,"Index",new{Category = cat.Category },new { @class = Request["Category"] == cat.Category ? "list-group-item active" : "list-group-item" })
            }
    </div>
</div>
<div class="col-md-10"></div>





@foreach (var item in Model.Product)
{

<div class="col-md-4" style="height:450px;padding:10px;margin:10px;border:solid thin whitesmoke">
    <div class="col-md-12">
        <img class="img" style="height:250px" src="~/Content/ProductImages/@item.Image" />
    </div>
    <div class="col-md-12">
        <strong>@Html.ActionLink(item.Name, "Details", new { id = item.Id })</strong>
    </div>
    <div class="col-md-12">
        <p>@item.Description</p>
    </div>
    <div class="col-md-12">
        <p>@item.Price</p>
    </div>
    <div class="col-md-12">
        <a href="@Url.Action("AddToBasket","Basket",new {Id=item.Id})" class="btn btn-default">Add to Basket</a>
    </div>
</div>
    }
<div class="col-md-12 clearfix"/>